### PR TITLE
fix: dist build

### PR DESCRIPTION
**Pull request by mattsb42-aws**
*Description of changes:*

Adding necessary dist build for action to work.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

### CODE REVIEW

**Comment by mattsb42-aws** [comment]
@seebees changes LGTM

**Comment by robin-aws** [comment]
Questions from someone with no familiarity with the distribution process:

1. How is dist/index.js generated, and what's the process for updating it? Should it be updated on every PR, or only when versions "released", if that makes sense?
2. Is there any sanity check I should be doing on index.js? GitHub won't even display it for me because of the size.
3. How can we have an integration test to verify a project can actually consume index.js successfully each time it's updated?

**Comment by seebees** [comment]
These are all super questions.
For most of this,
I would suggest that we build a workflow that uses this workflow...

(and `npm run publish` is the command that builds the dist)

**Comment by mattsb42-aws** [comment]
> How can we have an integration test to verify a project can actually consume index.js successfully each time it's updated?

For this one, we should add a self-test workflow. We should probably do that in a separate PR though.

**Comment by robin-aws** [comment]
To answer #1 myself after offline discussion: actions are versioned through tags, so only folks using aws-codebuild-run-build@master will pick this up immediately.

**Pull request merged**
